# hollow out to create enough space for the softdouble libs
MICROPY_PY_BLUETOOTH = 0
MICROPY_BLUETOOTH_NIMBLE = 0
MICROPY_BLUETOOTH_BTSTACK = 0
MICROPY_PY_LWIP = 0
MICROPY_PY_NETWORK_CYW43 = 0
MICROPY_PY_SSL = 0
MICROPY_SSL_MBEDTLS = 0
MICROPY_VFS_LFS2 = 0
FROZEN_MANIFEST = 

MICROPY_FLOAT_IMPL = double
# CFLAGS_EXTRA += -DMICROPY_HW_SPIFLASH_SIZE_BITS=128*1024*1024
