
#ifdef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_NEW_BOARD_NAME MICROPY_HW_BOARD_NAME " w/ double"
#undef MICROPY_HW_BOARD_NAME
#else
#define MICROPY_HW_NEW_BOARD_NAME "Micropython w/ double"
#endif

#define MICROPY_HW_BOARD_NAME MICROPY_HW_NEW_BOARD_NAME

#ifdef MICROPY_FLOAT_IMPL
#undef MICROPY_FLOAT_IMPL
#endif
#define MICROPY_FLOAT_IMPL (MICROPY_FLOAT_IMPL_DOUBLE)
