# hollow out to create enough space for the softdouble libs
LD_FILES = boards/esp8266_2MiB.ld
CFLAGS += -DMICROPY_ESP8266_512K
MICROPY_PY_ESPNOW = 0
MICROPY_PY_BTREE = 0
MICROPY_VFS_FAT = 0
MICROPY_VFS_LFS2 = 0
FROZEN_MANIFEST = 

MICROPY_FLOAT_IMPL = double

LIB_SRC_C += $(SRC_LIB_LIBM_DBL_C)
LIB_SRC_C += $(SRC_LIB_LIBM_DBL_SQRT_SW_C)

CFLAGS_EXTRA += -DMICROPY_FLOAT_IMPL=MICROPY_FLOAT_IMPL_DOUBLE
CFLAGS_EXTRA += -DMICROPY_OBJ_REPR=MICROPY_OBJ_REPR_B
CFLAGS_EXTRA += -fno-single-precision-constant -Wno-double-promotion
