MICROPY_FLOAT_IMPL = double
CFLAGS_EXTRA += -DMICROPY_FLOAT_IMPL=MICROPY_FLOAT_IMPL_DOUBLE
CFLAGS_EXTRA += -DMICROPY_OBJ_REPR=MICROPY_OBJ_REPR_B
CFLAGS_EXTRA += -fno-single-precision-constant -Wno-double-promotion